DomainSummary(
    hostname=Hostname(_value='atilova.com'),
    current=CurrentDnsTable(
        a=CurrentDnsRow(
            first_seen=FirstSeen(_value='2024-02-11'),
            values=(
                ARecord(
                    _value=ARecordValue(
                        ip=Ipv4(_value='104.21.74.244'),
                        count=Count(_value=0),
                        organization=Organization(_value='Cloudflare, Inc.')
                    )
                ),
                ARecord(
                    _value=ARecordValue(
                        ip=Ipv4(_value='172.67.207.241'),
                        count=Count(_value=0),
                        organization=Organization(_value='Cloudflare, Inc.')
                    )
                )
            )
        ),
        aaaa=CurrentDnsRow(
            first_seen=FirstSeen(_value='2024-02-11'),
            values=(
                AAAARecord(
                    _value=AAAARecordValue(
                        ipv6=Ipv6(_value='2606:4700:3032::ac43:cff1'),
                        count=Count(_value=0),
                        organization=None
                    )
                ),
                AAAARecord(
                    _value=AAAARecordValue(
                        ipv6=Ipv6(_value='2606:4700:3033::6815:4af4'),
                        count=Count(_value=0),
                        organization=None
                    )
                )
            )
        ),
        mx=None,
        ns=CurrentDnsRow(
            first_seen=FirstSeen(_value='2024-02-11'),
            values=(
                NSRecord(
                    _value=NSRecordValue(
                        nameserver=Nameserver(_value='shaz.ns.cloudflare.com'),
                        count=Count(_value=0),
                        organization=Organization(_value='Cloudflare, Inc.')
                    )
                ),
                NSRecord(
                    _value=NSRecordValue(
                        nameserver=Nameserver(_value='kurt.ns.cloudflare.com'),
                        count=Count(_value=0),
                        organization=Organization(_value='Cloudflare, Inc.')
                    )
                )
            )
        ),
        soa=CurrentDnsRow(
            first_seen=FirstSeen(_value='2024-02-11'),
            values=(
                SOARecord(
                    _value=SOARecordValue(
                        ttl=Ttl(_value=10000),
                        email=Email(_value='dns.cloudflare.com'),
                        count=Count(_value=0)
                    )
                ),
            )
        ),
        txt=None
    ),
    history=HistoryDnsTable(
        a=(
            HistoryDnsRow(
                first_seen=FirstSeen(_value='2024-02-11'),
                last_seen=LastSeen(_value='2024-06-10'),
                organizations=(Organization(_value='Cloudflare, Inc.'),),
                values=(
                    ARecord(
                        _value=ARecordValue(
                            ip=Ipv4(_value='104.21.74.244'),
                            count=Count(_value=0),
                            organization=None
                        )
                    ),
                    ARecord(
                        _value=ARecordValue(
                            ip=Ipv4(_value='172.67.207.241'),
                            count=Count(_value=0),
                            organization=None
                        )
                    )
                )
            ),
            HistoryDnsRow(
                first_seen=FirstSeen(_value='2024-02-01'),
                last_seen=LastSeen(_value='2024-02-10'),
                organizations=(Organization(_value='Namecheap, Inc.'),),
                values=(
                    ARecord(
                        _value=ARecordValue(
                            ip=Ipv4(_value='192.64.119.75'),
                            count=Count(_value=0),
                            organization=None
                        )
                    ),
                )
            )
        ),
        aaaa=(),
        mx=(
            HistoryDnsRow(
                first_seen=FirstSeen(_value='2024-02-01'),
                last_seen=LastSeen(_value='2024-02-10'),
                organizations=(Organization(_value='Namecheap, Inc.'),),
                values=(
                    MXRecord(
                        _value=MXRecordValue(
                            priority=Priority(_value=10),
                            host=Host(_value='eforward3.registrar-servers.com'),
                            count=Count(_value=None),
                            organization=None
                        )
                    ),
                    MXRecord(
                        _value=MXRecordValue(
                            priority=Priority(_value=10),
                            host=Host(_value='eforward2.registrar-servers.com'),
                            count=Count(_value=None),
                            organization=None
                        )
                    ),
                    MXRecord(
                        _value=MXRecordValue(
                            priority=Priority(_value=10),
                            host=Host(_value='eforward1.registrar-servers.com'),
                            count=Count(_value=None),
                            organization=None
                        )
                    ),
                    MXRecord(
                        _value=MXRecordValue(
                            priority=Priority(_value=15),
                            host=Host(_value='eforward4.registrar-servers.com'),
                            count=Count(_value=None),
                            organization=None
                        )
                    ),
                    MXRecord(
                        _value=MXRecordValue(
                            priority=Priority(_value=20),
                            host=Host(_value='eforward5.registrar-servers.com'),
                            count=Count(_value=None),
                            organization=None
                        )
                    )
                )
            ),
        ),
        ns=(
            HistoryDnsRow(
                first_seen=FirstSeen(_value='2024-02-11'),
                last_seen=LastSeen(_value='2024-06-10'),
                organizations=(Organization(_value='Cloudflare, Inc.'),),
                values=(
                    NSRecord(
                        _value=NSRecordValue(
                            nameserver=Nameserver(_value='kurt.ns.cloudflare.com'),
                            count=Count(_value=0),
                            organization=None
                        )
                    ),
                    NSRecord(
                        _value=NSRecordValue(
                            nameserver=Nameserver(_value='shaz.ns.cloudflare.com'),
                            count=Count(_value=0),
                            organization=None
                        )
                    )
                )
            ),
            HistoryDnsRow(
                first_seen=FirstSeen(_value='2024-02-01'),
                last_seen=LastSeen(_value='2024-02-10'),
                organizations=(
                    Organization(_value='Neustar Security Services'),
                    Organization(_value='NeuStar, Inc.')
                ),
                values=(
                    NSRecord(
                        _value=NSRecordValue(
                            nameserver=Nameserver(_value='dns1.registrar-servers.com'),
                            count=Count(_value=0),
                            organization=None
                        )
                    ),
                    NSRecord(
                        _value=NSRecordValue(
                            nameserver=Nameserver(_value='dns2.registrar-servers.com'),
                            count=Count(_value=0),
                            organization=None
                        )
                    )
                )
            )
        ),
        soa=(
            HistoryDnsRow(
                first_seen=FirstSeen(_value='2024-02-11'),
                last_seen=LastSeen(_value='2024-06-10'),
                organizations=(Organization(_value='Cloudflare, Inc.'),),
                values=(
                    SOARecord(
                        _value=SOARecordValue(
                            ttl=Ttl(_value=10000),
                            email=Email(_value='dns.cloudflare.com'),
                            count=Count(_value=0)
                        )
                    )
                )
            ),
            HistoryDnsRow(
                first_seen=FirstSeen(_value='2024-02-01'),
                last_seen=LastSeen(_value='2024-02-10'),
                organizations=(Organization(_value='Namecheap, Inc.'),),
                values=(
                    SOARecord(
                        _value=SOARecordValue(
                            ttl=Ttl(_value=43200),
                            email=Email(_value='hostmaster.registrar-servers.com'),
                            count=Count(_value=0)
                        )
                    )
                )
            )
        ),
        txt=(
            HistoryDnsRow(
                first_seen=FirstSeen(_value='2024-02-01'),
                last_seen=LastSeen(_value='2024-02-10'),
                organizations=(),
                values=(
                    TXTRecord(
                        _value=TXTRecordValue(
                            value=Txt(_value='v=spf1 include:spf.efwd.registrar-servers.com ~all')
                        )
                    ),
                )
            ),
        )
    ),
    subdomains=(
        SubDomain(_value='aws'),
        SubDomain(_value='proxy'),
        SubDomain(_value='gateway'),
        SubDomain(_value='www')
    )
)
